### ISSUE TITLE
tomatoist should remember who I am

### ISSUE THREAD

**Issue by dgryski** [mrmemes-eth/tomatoist#6]
I have a bookmark in my toolbar to tomatoi.st/dgryski.  I was hoping I could configure the app launcher to do the same thing, but the URL is hard coded to / which means I get a random session each time.

**Comment by mrmemes-eth** [comment]
Is this in relation to the SSB or the Chrome App button?

**Comment by dgryski** [comment]
The Chrome App button has no configuration option.

**Comment by mrmemes-eth** [comment]
Yes, quite right. This was a limitation of the app store at the time, but the capabilities have since changed. I'll have a look-see and try to figure it out.

**Comment by mrmemes-eth** [comment]
So there doesn't appear to be any way to take configuration options for hosted apps, unlike extensions. This problem could be solved via some light usage of a persistent cookie though. I'll take a stab at it and let you know.

**Comment by mrmemes-eth** [comment]
This should be fixed in the current deployed version. Tomatoi.st now remembers the last session you visited and will go there again when you start it up. Please take a look and let me know if it works as you expect it to.

Cheers!

**Comment by dgryski** [comment]
Works great!

Thanks

**Comment by mrmemes-eth** [comment]
Awesome :)
