### ISSUE TITLE
Zippy for Webstore -- how to verify that it works?

### ISSUE THREAD

**Issue by kytrinyx** [mrmemes-eth/tomatoist#9]
I was thinking of going over the gems/dependencies and upgrading where possible.

Zippy is now at 0.2.1 and the project is currently on 0.1.0 -- how would I check that the rake task for packaging tomatoist for the webstore actually works?

(... aaaand what is this webstore of which you speak?)

**Comment by mrmemes-eth** [comment]
Hi @kytrinyx :)

So the web store in question is the [Chrome Web Store](https://chrome.google.com/webstore/category/apps). That task merely facilitates easy packaging of the app assets that are specific to the bundling for the web store... It's woefully out of date though (as you've no doubt noticed) and I'm not even sure that it's still building the package in the right format. In any case, Zippy is fine to update or even sub out for another library (as it seems @novohispano may have already done) if it's more convenient or has a better API.

Cheers,
Stephen

**Comment by mrmemes-eth** [comment]
Oh! and as to how to verify it actually works: if it outputs an extractable zip file named "tomatoist.zip" in the root of the app, then it works :)

**Comment by kytrinyx** [comment]
Awesome, thank you :)

I don't think @novohispano sub'd out zippy, just made a dependency explicit.

**Comment by mrmemes-eth** [comment]
Cheers, I just glanced at it and noted the addition of rubyzip and thought it was a substitution. Also, just ran with the pull request he submitted and the pkg task still works as expected.

Thanks :)

**Comment by kytrinyx** [comment]
Cool! Closing, since all this really was, was a request for documentation. Thanks for your help!
